version: '3.7'

services:

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   # volumes:
  #   #   - '.:/app'
  #   #   - '/app/node_modules'
  #   #   - './frontend/src:/usr/app/frontend/src'
  #   ports:
  #     - 8081:8081
  #   command: sh -c "npm run serve"
  #   # environment:
  #   #   - CHOKIDAR_USEPOLLING=true
  #   networks:
  #     - agent-protal
    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/backend/node_modules'
      - './backend/:/usr/app/backend'
    ports:
      - "8041:3001"
    command: sh -c "npm install && npm run dev"
    # command: sh -c "npm run dev"
    environment:
      NODE_ENV: dev
      TZ: Asia/Calcutta
    networks:
      - agent-portal
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Agent_Care
      MYSQL_USER: agentportal
      MYSQL_PASSWORD: agentportal
    ports:
      - "3310:3306"
    networks:
      - agent-portal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8042:80"
    networks:
      - agent-portal
  
networks:
  agent-portal:
    driver: bridge
volumes:
  db_data: {}