version: '3.7'

services:

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   # volumes:
  #   #   - '.:/app'
  #   #   - '/app/node_modules'
  #   #   - './frontend/src:/usr/app/frontend/src'
  #   ports:
  #     - 8081:8081
  #   command: sh -c "npm run serve"
  #   # environment:
  #   #   - CHOKIDAR_USEPOLLING=true
  #   networks:
  #     - agent-protal
    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # - '.:/app'
      # - '/app/backend/node_modules'
      # - './backend/:/usr/app/backend'
    ports:
      - "8041:3001"
    command: sh -c "npm install && npm run dev"
    # command: sh -c "npm run dev"
    environment:
      NODE_ENV: dev
      TZ: Asia/Calcutta
    networks:
      - agent-portal
  
  
networks:
  agent-portal:
    driver: bridge
volumes:
  db_data: {}